return {}
-- return {
--   "nvimtools/none-ls.nvim",
--   event = "LazyFile",
--   dependencies = { "mason.nvim" },
--   opts = function(_, opts)
--     local nls = require("null-ls")
--
--     opts.root_dir = opts.root_dir
--       or require("null-ls.utils").root_pattern(".null-ls-root", ".neoconf.json", "Makefile", "dune-project")
--
--     opts.sources = vim.list_extend(opts.sources or {}, {
--       nls.builtins.formatting.stylua,
--       nls.builtins.formatting.ocamlformat,
--       nls.builtins.diagnostics.eslint,
--     })
--   end,
-- }
